# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Upload build artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: pingbot-binary
        path: ./
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: pingbot-binary
          path: pingbot-binary
      - name: Deploy artifact
        uses: garygrossgarten/github-action-scp@release
        with:
          local: pingbot-binary
          remote: /apps/pingbot/pingbot-binary
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_HOST_SSH_USER }}
          password: ${{ secrets.DEPLOY_HOST_SSH_PASSWORD }}
